---------------------------------------------
title: "LAB 29"
author: "JESSICA PAOLA AGUILAR SERVIN"
date: "2023-02-24"
output: html_document
-----------------------------------------------
###########################################################################

Laboratorio_29_dplyr

##########################################################################
--------------------------------------------------------------------------

Elaborado por la alumna JESSICA PAOLA AGUILAR SERVIN.
    
Excluir valores perdidos de los análisis
How to sum a variable by group in R
  
Cargar datos 2013
```{r}
library(data.table)
library(dplyr)
```

SUMA DE VARIABLES DE ACUERDO AL GRUPO QUE PERTENEZCA
RUTA DE DATOS
```{r}
choose.files()
```


```{r}
data2013 <- read.csv("C:\\Users\\gusta\\OneDrive\\Documents\\GitHub\\JPAS_LABS29\\INPUT\\greenR_2013.csv")

data2013 <- as.data.table(data2013)
```


Para saber que clase de datos son
```{r}
class(data2013)
```

Suma de variables DATOS AGRUPADOS
```{r}
resultados2013 <- data2013 %>% 
  group_by(location_name) %>% 
  summarise(suma_GCI_2013 = sum(GCI_2013, na.rm = T),
            suma_GP_SINVCR = sum(GP_SINVCR, na.rm = T),
            suma_GCP_2013 = sum(GCP_2013, na.rm = T),
            count = n())
```

EXPORTAR RESULATDOS
```{r}
write.csv(data2013, file = "LAB29_DATA2013.cvs")
write.csv(resultados2013, file = "LAB29_RESULTADOS2013.cvs")
```

